// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApi68YhyHladlwRvMTa7M8F_mOwcEHAnQ',
    appId: '1:1079259920025:web:2ce64d8903bc2fede6aa08',
    messagingSenderId: '1079259920025',
    projectId: 'flutterfirebase-7fe99',
    authDomain: 'flutterfirebase-7fe99.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-7fe99-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7fe99.appspot.com',
    measurementId: 'G-0274H0WPTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqRFHpGPzdntTCeehD1gNZplLaIDaZIdY',
    appId: '1:1079259920025:android:5ccc8e08de1e350ae6aa08',
    messagingSenderId: '1079259920025',
    projectId: 'flutterfirebase-7fe99',
    databaseURL: 'https://flutterfirebase-7fe99-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7fe99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObMFsIbhCurkmZnOj8yG5Q2w5xjNS6bQ',
    appId: '1:1079259920025:ios:5b07278c0a4df240e6aa08',
    messagingSenderId: '1079259920025',
    projectId: 'flutterfirebase-7fe99',
    databaseURL: 'https://flutterfirebase-7fe99-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7fe99.appspot.com',
    iosClientId: '1079259920025-cuj8nn8t02n7i0vlgaceap1vt7e980u0.apps.googleusercontent.com',
    iosBundleId: 'com.sahil.fcmMobileWeb',
  );
}
